### ISSUE TITLE
Issues in Reagge

### ISSUE THREAD

**Issue by zaborowska** [CALMmodel/CALM#20]
E<0 for some particles
strange error in boost matrix

**Comment by majanik** [comment]
Can be taken care of if TF1 Ptot function creation moved to the constructor.
You also have to make sure the Total energy value is inside a  probable range (ie. total energy > sum of masses)

**Comment by majanik** [comment]
Resolved for now: they both happen sometimes still.
Fixed: in case of negative energy, the momentum is distributed again.
Error in boost matrix is very uncommon and according to the author comes from some rounding errors. Ignored at the moment.
