### ISSUE TITLE
Correct Total Momentum of particles produced

### ISSUE THREAD

**Issue by majanik** [CALMmodel/CALM#24]
Whatever is produced it should match the TF1 we give as an input.
Right now it is not (checked for "minijets")

For minijets local the masses of the particles should be added separately to the energy, not to take from the momentum distribution [done for minijets, but not minijets Local]

**Comment by zaborowska** [comment]
Total momentum is not invariant. Total energy is (and vector momentum). Hence, total energy distribution used as an input. For instnance generated with pythia (possibility to choose only particles that one is generating)
